/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2023-07-26 05:28:21 
*/
import FluentBulletBase, { ConditionFieldType } from "./fluent-bullet-base";
import { IWrapperFlow } from "./i-wrapper-flow";
import WrapperFlow from "./wrapper-flow";
import { WrapperFlowBuilder } from "./wrapper-flow-builder";
import WrapperStopIf from "./wrapper-stop-if";


