// import { FlowFunctionType, IBulletFlowApi } from "./facade";

/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2023-07-26 05:26:06 
*/
export interface IPage {
    itemsOnPage(value: number): this;
    pageNo(value: number): this;
    repeat(value: boolean): this;
    // flow(flowBuilder: FlowFunctionType): IBulletFlowApi;

}
